RecipeSource.create!([
  {name: "The Minimalist Baker", link: "http://minimalistbaker.com", scrape_name: "h1.entry-title", scrape_ingredient: ".ingredient", scrape_image: ".entry-content img", slug: "minimalistbaker.com"},
  {name: "Half Baked Harvest", link: "http://halfbakedharvest.com", scrape_name: "h1.post-title", scrape_ingredient: ".wprm-recipe-ingredient", scrape_image: ".post-content img", slug: "halfbakedharvest.com"},
  {name: "Smitten Kitchen", link: "http://smittenkitchen.com", scrape_name: "h1.entry-title > a", scrape_ingredient: ".jetpack-recipe-ingredient", scrape_image: ".post-thumbnail-container > img", slug: "smittenkitchen.com"},
  {name: "All Recipes", link: "http://allrecipes.com", scrape_name: ".recipe-summary__h1", scrape_ingredient: ".recipe-ingred_txt", scrape_image: ".rec-photo", slug: "allrecipes.com"},
  {name: "Epicurious", link: "http://epicurious.com", scrape_name: "h1", scrape_ingredient: ".ingredient-item", scrape_image: "picture", slug: "epicurious.com"},
  {name: "Delish", link: "http://delish.com", scrape_name: "h1.content-hed.recipe-hed", scrape_ingredient: ".ingredient-item", scrape_image: "img", slug: "delish.com"},
  {name: "My Recipes", link: "http://myrecipes.com", scrape_name: "h1.headline", scrape_ingredient: ".ingredients li", scrape_image: "", slug: "myrecipes.com"},
  {name: "Genius Kitchen", link: "http://geniuskitchen.com", scrape_name: ".recipe-header h1", scrape_ingredient: ".ingredient-list li", scrape_image: "", slug: "geniuskitchen.com"},
  {name: "Tasty", link: "http://tasty.co", scrape_name: "h1.recipe-name", scrape_ingredient: ".ingredients__section li", scrape_image: "", slug: "tasty.co"},
  {name: "The Pioneer Woman", link: "http://thepioneerwoman.com", scrape_name: "h2.entry-title", scrape_ingredient: ".list-ingredients li", scrape_image: ".featured-image img", slug: "thepioneerwoman.com"},
  {name: "The Kitchn", link: "http://thekitchn.com", scrape_name: "h1.PostHeader__headline", scrape_ingredient: ".PostRecipeIngredientGroup__ingredient", scrape_image: ".PostPicture__picture img", slug: "thekitchn.com"},
  {name: "Food Network", link: "http://foodnetwork.com", scrape_name: "h1.o-AssetTitle__a-Headline", scrape_ingredient: ".o-Ingredients__a-ListItemText", scrape_image: "", slug: "foodnetwork.com"},
  {name: "Food 52", link: "http://food52.com", scrape_name: "h1.article-header-title", scrape_ingredient: ".recipe-list li", scrape_image: "#recipe-gallery-frame img", slug: "food52.com"},
  {name: "yummly", link: "http://yummly.com", scrape_name: ".primary-info-text h1", scrape_ingredient: ".IngredientLine", scrape_image: "", slug: "yummly.com"},
  {name: "ChowHound", link: "http://chowhound.com", scrape_name: "h1", scrape_ingredient: "li[itemprop=\"ingredients]", scrape_image: "", slug: "chowhound.com"},
  {name: "Simply Recipes", link: "http://simplyrecipes.com", scrape_name: "h1.entry-title", scrape_ingredient: "li.ingredient", scrape_image: ".featured-image img", slug: "simplyrecipes.com"},
  {name: "Cooking Light", link: "http://cookinglight.com", scrape_name: "h1.headline", scrape_ingredient: ".ingredients li", scrape_image: ".image-container img", slug: "cookinglight.com"},
  {name: "Betty Crocker", link: "http://bettycrocker.com", scrape_name: ".recipePartTitle h1", scrape_ingredient: ".recipePartIngredient", scrape_image: ".recipePartRecipeImage img", slug: "bettycrocker.com"},
  {name: "Eating Well", link: "http://eatingwell.com", scrape_name: ".recipeDetailSummaryDetails h3.recipeDetailHeader", scrape_ingredient: "span[itemprop=\"ingredients\"]", scrape_image: "img.recipeDetailSummaryImageMain", slug: "eatingwell.com"},
  {name: "Cooks", link: "http://cooks.com", scrape_name: ".title", scrape_ingredient: ".ingredient", scrape_image: "", slug: "cooks.com"},
  {name: "Kraft Recipes", link: "http://kraftrecipes.com", scrape_name: "h1#khMainTitle", scrape_ingredient: "span[itemprop=\"recipeIngredient\"]", scrape_image: "", slug: "kraftrecipes.com"},
  {name: "Serious Eats", link: "http://seriouseats.com", scrape_name: "h1.recipe-title", scrape_ingredient: ".ingredient", scrape_image: ".recipe-main-photo img", slug: "seriouseats.com"},
  {name: "Low Carb Yum", link: "http://lowcarbyum.com", scrape_name: ".entry-header h1.entry-title", scrape_ingredient: ".wprm-recipe-ingredient", scrape_image: ".entry-content img", slug: "lowcarbyum.com"},
  {name: "iFoodReal", link: "http://ifoodreal.com", scrape_name: "h1.entry-title", scrape_ingredient: ".ifoodreal-recipe-ingredients li", scrape_image: ".entry-content img", slug: "ifoodreal.com"},
  {name: "Ambitious Kitchen", link: "http://ambitiouskitchen.com", scrape_name: "h1.entry-title", scrape_ingredient: ".ERSIngredients li", scrape_image: ".entry_content p img", slug: "ambitiouskitchen.com"},
  {name: "Dinner at the Zoo", link: "http://dinneratthezoo.com", scrape_name: "h1.entry-title", scrape_ingredient: ".wprm-recipe-ingredient", scrape_image: ".entry-content p img", slug: "dinneratthezoo.com"},
  {name: "Damn Delicious", link: "http://damndelicious.net", scrape_name: ".post-title h1", scrape_ingredient: ".ingredient", scrape_image: ".post p img", slug: "damndelicious.net"},
  {name: "The Girl on Bloor", link: "http://thegirlonbloor.com", scrape_name: "h1.entry-title", scrape_ingredient: ".wpurp-responsive-desktop .wpurp-recipe-ingredient-container .wpurp-recipe-ingredient", scrape_image: ".entry-content p img", slug: "thegirlonbloor.com"}
])
